export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';


export const FETCH_QUESTION_PENDING = 'FETCH_QUESTION_PENDING';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAILED = 'FETCH_QUESTION_FAILED';


export const CHECK_QUESTION_ANSWER = 'CHECK_QUESTION_ANSWER';
export const REQUEST_QUESTION_HINT = 'REQUEST_QUESTION_HINT';


export const FETCH_STYLE_RANGE_PENDING = 'FETCH_STYLE_RANGE_PENDING';
export const FETCH_STYLE_RANGE_SUCCESS = 'FETCH_STYLE_RANGE_SUCCESS';
export const FETCH_STYLE_RANGE_FAILED = 'FETCH_STYLE_RANGE_FAILED';


export const SET_STYLE_RANGE_ANSWER = 'SET_STYLE_RANGE_ANSWER';
export const CHECK_STYLE_RANGE_ANSWER = 'CHECK_STYLE_RANGE_ANSWER';


export const SET_PAGE_ID = 'SET_PAGE_ID';

